'use strict'

import {
  STRENGTH, DEXTERITY, INTELLIGENCE, WISDOM, CHARISMA
} from './abilities.js'

export const ACROBATICS = 'ACROBATICS'
export const ANIMAL_HANDLING = 'ANIMAL_HANDLING'
export const ARCANA = 'ARCANA'
export const ATHLETICS = 'ATHLETICS'
export const DECEPTION = 'DECEPTION'
export const HISTORY = 'HISTORY'
export const INSIGHT = 'INSIGHT'
export const INTIMIDATION = 'INTIMIDATION'
export const INVESTIGATION = 'INVESTIGATION'
export const MEDICINE = 'MEDICINE'
export const NATURE = 'NATURE'
export const PERCEPTION = 'PERCEPTION'
export const PERFORMANCE = 'PERFORMANCE'
export const PERSUASION = 'PERSUASION'
export const RELIGION = 'RELIGION'
export const SLEIGHT_OF_HAND = 'SLEIGHT_OF_HAND'
export const STEALTH = 'STEALTH'
export const SURVIVAL = 'SURVIVAL'

export const SKILL_ABILITY = {
  [ACROBATICS]: DEXTERITY,
  [ANIMAL_HANDLING]: WISDOM,
  [ARCANA]: INTELLIGENCE,
  [ATHLETICS]: STRENGTH,
  [DECEPTION]: CHARISMA,
  [HISTORY]: INTELLIGENCE,
  [INSIGHT]: WISDOM,
  [INTIMIDATION]: CHARISMA,
  [INVESTIGATION]: INTELLIGENCE,
  [MEDICINE]: WISDOM,
  [NATURE]: INTELLIGENCE,
  [PERCEPTION]: WISDOM,
  [PERFORMANCE]: CHARISMA,
  [PERSUASION]: CHARISMA,
  [RELIGION]: INTELLIGENCE,
  [SLEIGHT_OF_HAND]: DEXTERITY,
  [STEALTH]: DEXTERITY,
  [SURVIVAL]: WISDOM
}

export const SKILLS = [
  ACROBATICS,
  ANIMAL_HANDLING,
  ARCANA,
  ATHLETICS,
  DECEPTION,
  HISTORY,
  INSIGHT,
  INTIMIDATION,
  INVESTIGATION,
  MEDICINE,
  NATURE,
  PERCEPTION,
  PERFORMANCE,
  PERSUASION,
  RELIGION,
  SLEIGHT_OF_HAND,
  STEALTH,
  SURVIVAL
]
