'use strict'

export const ACROBATICS = 'ACROBATICS'
export const ANIMAL_HANDLING = 'ANIMAL_HANDLING'
export const ARCANA = 'ARCANA'
export const ATHLETICS = 'ATHLETICS'
export const DECEPTION = 'DECEPTION'
export const HISTORY = 'HISTORY'
export const INSIGHT = 'INSIGHT'
export const INTIMIDATION = 'INTIMIDATION'
export const INVESTIGATION = 'INVESTIGATION'
export const MEDICINE = 'MEDICINE'
export const NATURE = 'NATURE'
export const PERCEPTION = 'PERCEPTION'
export const PERFORMANCE = 'PERFORMANCE'
export const PERSUASION = 'PERSUASION'
export const RELIGION = 'RELIGION'
export const SLEIGHT_OF_HAND = 'SLEIGHT_OF_HAND'
export const STEALTH = 'STEALTH'
export const SURVIVAL = 'SURVIVAL'

export const SKILLS = [
  ACROBATICS,
  ANIMAL_HANDLING,
  ARCANA,
  ATHLETICS,
  DECEPTION,
  HISTORY,
  INSIGHT,
  INTIMIDATION,
  INVESTIGATION,
  MEDICINE,
  NATURE,
  PERCEPTION,
  PERFORMANCE,
  PERSUASION,
  RELIGION,
  SLEIGHT_OF_HAND,
  STEALTH,
  SURVIVAL
]
